nhost/hasura-auth

src/ts-start.ts
Always apply metadata. Hasura Auth should be in total control of the `auth` schema and GraphQL metadata.
=> Always apply metadata

src/routes/signup/email-password.ts, src/routes/user/email/send-verification-email.ts, src/routes/user/password.ts
- https://nhost.atlassian.net/browse/NHOST-612
=> Increase signup's ticket expires at to 30 days

src/routes/signin/passwordless/email.ts, src/utils/user/deanonymize-passwordless-email.ts
I'm guessing this is just a typo. Saw it in the email link and couldn't help but fix it lol.
=> Correct typos

email-templates/fr/email-confirm-change/body.html, email-templates/fr/email-confirm-change/subject.txt, email-templates/fr/email-verify/body.html, email-templates/fr/email-verify/subject.txt, email-templates/fr/password-reset/body.html, email-templates/fr/password-reset/subject.txt, email-templates/fr/signin-passwordless/body.html, email-templates/fr/signin-passwordless/subject.txt
The goal of this PR is to have email templates in French
=> feat(emails): translate email templates to french

.github/workflows/release.yml, .husky/commit-msg, .release-it.json, package.json, yarn.lock
Commit / version / release pipeline
Will push to main so GH can be tested
Will remove generated versions if not perfect
=> versioning

.gitignore, docker-compose.yaml, docker/initdb.d/0001-create-schema.sql
=> chore: use official postgres image

src/metadata.ts
Workaround of a bug in Hasura: https://github.com/hasura/graphql-engine/issues/8020
fix #76
=> fix(metadata): show column values when the column name is the same as the graphql field name

.github/workflows/build.yml, src/utils/env.ts, src/utils/roles.ts, test/routes/signin/passwordless/email.test.ts, test/routes/signup/email-password.test.ts
=> refactor: remove references to the ALLOWED_USER_ROLES unused environment variable

.github/workflows/publish.yml
The full name for hasura-auth in our ECR is the following:
*****************.dkr.ecr.eu-central-1.amazonaws.com/hasura-auth
=> Fix ECR repo name

src/helpers.ts, src/routes/signin/passwordless/email.ts, src/routes/signin/providers/utils.ts, src/routes/signup/email-password.ts, src/routes/user/email/change.ts, src/routes/user/email/send-verification-email.ts, src/routes/user/password-reset.ts, src/utils/user/deanonymize-email-password.ts, src/utils/user/deanonymize-passwordless-email.ts
apply isValidRedirectTo in Oauth as well, and simplify its signature
=> fix: allow redirect urls in Oauth that starts with the one defined in the server

Dockerfile
This pr is rather meant to share what I just learnt - and to make things a bit cleaner
=> chore: enable pnpm post-install script

src/routes/verify/verify.ts, src/utils/index.ts
- Don't put two hashes to URL
- Only add `?` or `&` if needed
=> fix: 0.4.0 bugs

src/gql/users.graphql, src/openapi/responses.ts, src/routes/user/mfa.ts, src/types.ts, src/utils/__generated__/graphql-request.ts, src/utils/user/getters.ts, src/validation/fields.ts
See https://github.com/nhost/nhost/issues/306
=> feat: add `emailVerified`, `phoneNumber`, `phoneNumberVerified`, and `activeMfaType` to User

CHANGELOG.md, src/middleware/auth.ts, src/utils/jwt/generate.ts, src/utils/jwt/get-claims.ts, src/utils/jwt/index.ts, test/utils.ts
By convention, Hasura claim names are kebab-case.
close #126
=> Rename the JWT claim `x-hasura-isAnonymous` to `x-hasura-is-anonymous`

src/routes/signin/passwordless/email.ts, src/routes/signup/email-password.ts, src/routes/user/email/change.ts, src/routes/user/email/send-verification-email.ts, src/routes/user/password-reset.ts, src/routes/verify/verify.ts, src/types.ts, src/utils/user/deanonymize-email-password.ts, src/utils/user/deanonymize-passwordless-email.ts, src/validation/fields.ts
Closes https://github.com/nhost/hasura-auth/issues/54
=> refactor: improve "email types" typings

src/metadata.ts
also make sure metadata is reloaded if the metadata script failed in the
=> Fix: run a metadata reload before and after applying hasura-auth metadata

src/openapi/index.ts, src/routes/token/index.ts, src/routes/token/token.ts, src/routes/token/verify.ts, src/utils/tokens.ts, src/validation/fields.ts
- Partially solves #65
- Closes #83
=> feat: add JWT verify endpoint and getToken improvements

src/validation/fields.ts, test/routes/misc/options.test.ts
=> fix: check locales are not more than two characters

src/env-vars-check.ts, src/routes/signin/passwordless/email.ts, src/routes/signin/passwordless/sms/otp.ts, src/routes/signin/passwordless/sms/sms.ts, src/utils/twilio.ts
- Add support for Twilio Verify based on the SID use messing or verify APIs
- Closes #79, 
- Closes #99
=> fix: passwordless authentication fixes and improvements

DEVELOPERS.md, Makefile, docs/openapi.json, package.json
=> chore: simplify developers commands, including the generation of the OpenAPI specs

src/utils/jwt/custom-claims.ts, test/routes/misc/custom-claims.test.ts
=> fix: use the metadata field in custom claims

src/utils/jwt/custom-claims.ts, test/routes/misc/custom-claims.test.ts
=> fix: do not add null values to custom claims

src/routes/signin/index.ts, src/routes/signin/passwordless/email.ts, src/routes/signin/passwordless/sms/otp.ts, src/routes/signin/passwordless/sms/sms.ts, src/routes/signin/webauthn.ts, src/routes/signup/index.ts, src/routes/signup/webauthn.ts, src/routes/token/index.ts, src/routes/user/deanonymize.ts, src/routes/user/index.ts, src/routes/user/webauthn.ts, src/types.ts, src/validation/fields.ts
- 0 change in the application logic
- improve typings
- improve automatically generated OpenApi doc
- flag missing payload definitions in the OpenApi doc
=> Improve typings

package.json, src/routes/verify/verify.ts, src/utils/redirect.ts, test/routes/misc/options.test.ts
=> fix: 🐛 don't break reditection with redirectTo and params

src/metadata.ts
drop metadata inconsistency **if and only if** they are related to the authenticators to security key name change
=> fix: drop authenticators inconsistency safely

docs/configuration.md
- [Schema](https://github.com/nhost/hasura-auth/blob/main/docs/schema.md). The schema in a [Mermaid ER diagram](https://mermaid-js.github.io/mermaid/#/entityRelationshipDiagram)
- …
=> Update environment variables link

src/routes/signup/email-password.ts
=> Corrected comment

src/validation/fields.ts, test/routes/signup/email-password.test.ts
Closes https://github.com/nhost/hasura-auth/issues/245
=> fix: return Have I Been Pwned error message

src/routes/mfa/totp-generate.ts
Closes #220 
- [Schema](https://github.com/nhost/hasura-auth/blob/main/docs/schema.md). The schema in a [Mermaid ER diagram](https://mermaid-js.github.io/mermaid/#/entityRelationshipDi …
=> fix(otp): increase OTP secret entropy to 256 bits

src/validation/fields.ts
fixes https://github.com/nhost/hasura-auth/issues/273.
^ couldn't get tests to run in the first place, so unsure if they pass.
=> Prevent `Joi` from Converting `redirectTo` to Lowercase

.changeset/neat-years-help.md, .changeset/ten-hats-warn.md, .changeset/tender-masks-grin.md, src/routes/oauth/config.ts, src/routes/oauth/index.ts, src/routes/oauth/utils.ts
=> fix: 🐛 adjust grant

.changeset/eighty-months-grin.md, .github/workflows/test.yaml, docker-compose.yaml, src/routes/oauth/index.ts
Solves https://github.com/nhost/nhost/issues/1353
=> fix: preserve the Oauth session between the initial request and the callback

.changeset/quiet-berries-develop.md, src/utils/env.ts
=> refactor: allow implicit allowed roles/locales

src/routes/oauth/index.ts
The very first time a github user signs in with Hasura-Auth, an error was returned. The user had to click a second time on "Signin with Github" to make it work.
This PR fixes the issue.
=> fix: no refresh token for a new first-time user

.changeset/clever-pianos-bake.md, email-templates/es/email-confirm-change/body.html, email-templates/es/email-confirm-change/subject.txt, email-templates/es/email-verify/body.html, email-templates/es/email-verify/subject.txt, email-templates/es/password-reset/body.html, email-templates/es/password-reset/subject.txt, email-templates/es/signin-passwordless-sms/body.txt, email-templates/es/signin-passwordless/body.html, email-templates/es/signin-passwordless/subject.txt
Added suppor for Spanish language email templates
- [Schema](https://github.com/nhost/hasura-auth/blob/main/docs/schema.md). The schema in a [Mermaid ER …
=> feat: 🎸 translate email templates to spanish

package.json, src/validation/fields.ts, test/validation.test.ts
- introduces back the support for using wildcards, `*`, in allowed redirect URLs while keeping a fix for the domain shadowing issue found.
=> allow wildcard urls

.changeset/popular-doors-rhyme.md
- add missing changeset for https://github.com/nhost/hasura-auth/pull/353
=> add missing changeset

.github/workflows/changesets.yaml
=> fix(ci): update GitHub workflow to push to Docker Hub with git tag

.changeset/sour-dodos-mix.md, src/routes/oauth/config.ts
fixes https://github.com/nhost/nhost/issues/2364
=> fix: update linkedin oauth provider configuration

.changeset/brown-shoes-pump.md, src/utils/hasura-metadata/helpers.ts
=> fix: make sure existing modified permissions are not overwritten

.changeset/seven-scissors-poke.md, src/routes/oauth/index.ts
=> fix: parse metadata during the oauth callback

.changeset/tough-cheetahs-admire.md, src/validation/fields.ts, src/validation/validators/email.ts
=> fix: replace helper.error with helper.message due to joi's breaking changes

src/routes/oauth/index.ts
=> fix: grant: respect dynamic options

go/cmd/jwt_getter.go, go/controller/change_env.go, go/controller/custom_claims.go, go/controller/custom_claims_test.go, go/controller/errors.go, go/controller/post_signup_email_password.go, go/controller/post_signup_email_password_test.go, go/controller/post_signup_webauthn.go, go/controller/post_signup_webauthn_test.go, go/controller/post_signup_webauthn_verify_test.go, go/controller/workflows.go, test/routes/misc/custom-claims.test.ts
This massively increases postgres performance under heavy load by avoiding locks.
=> fix: remove as many RTTs to postgres as possible

go/controller/custom_claims.go, go/controller/custom_claims_test.go
Fixes https://github.com/nhost/nhost/issues/2658
=> fix: special treatment to custom claims for backwards compatibility

.github/workflows/checks.yaml, .github/workflows/codeql-analysis.yml, flake.lock
CI is broken due to the pull_request_target... won't be fixed until it is merged.
=> chore: update nixops and allow running CI with secrets for contributors

.golangci.yaml, docs/cli.md, go/cmd/email.go, go/cmd/serve.go, go/controller/controller.go, go/controller/elevate_webauthn_test.go, go/controller/mock/controller.go, go/controller/refresh_token_test.go, go/controller/secrets.go, go/controller/sign_in_email_password.go, go/controller/sign_in_otp_email.go, go/controller/sign_in_otp_email_test.go, go/controller/sign_in_passwordless_email.go, go/controller/sign_in_passwordless_email_test.go, go/controller/sign_in_passwordless_sms.go, go/controller/sign_in_passwordless_sms_test.go, go/controller/sign_in_provider_callback_get_test.go, go/controller/sign_up_email_password.go, go/controller/sign_up_email_password_test.go, go/controller/verify_elevate_webauthn_test.go, go/controller/workflows_tickets.go, go/notifications/sms/dev.go, go/notifications/sms/sms.go, go/notifications/sms/twilio_sms.go, go/sql/query.sql, go/sql/query.sql.go, go/testhelpers/gocmp.go
Enhancement, Bug fix
___
- Add configurable SMS provider flag
- Simplify OTP generation and storage
- Update SQL to cryptographically verify OTP
- Refactor and export password hash verifier
___
```mermaid
flowchart LR
A["CLI --sms-provider flag"]
B["getSMS initializes provider"]
C["Dev or Twilio backend"]
D["SendVerificationCode generates OTP"]
E["DB stores and verifies OTP using crypt"]
A -- "provides flag" --> B
B -- "selects provider" --> C
C -- "sends code" --> D
D -- "calls DB update" --> E
```
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>9 files</summary><table>
<tr>
<td><strong>email.go</strong><dd><code>Add SMS provider switch …
=> fix: use postgres crypt to handle OTP hashing
